server:
    port: 8080

spring:
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
        throw-exception-if-no-handler-found: true
    h2:
        console:
            path: /h2-console
            enabled: true
            settings:
                web-allow-others: true
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:~/api;auto_server=true
        username: sa
        password:
    jpa:
        database: H2
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
    web:
        resources:
            add-mappings: false
    redis:
        host: localhost
        port: 6379



