server:
    port: 8080

spring:
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    h2:
        console:
            path: /h2-console
            enabled: true
            settings:
                web-allow-others: true
        driver-class-name: org.h2.Driver
        url: jdbc:h2:~/member-data;auto_server=true
        username: sa
        password:



